name: notebook
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.6.1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  sqflite: ^2.3.2
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2
  cloud_firestore: ^5.1.0
  google_mobile_ads: ^5.1.0
  firebase_analytics: ^11.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/notebook-2.png
    - i18n/en.json
    - i18n/uk.json
  #   - images/a_dot_ham.jpeg

